name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install pipenv
        run: python3 -m pip install pipenv
      - run: pipenv lock
      - name: Install dependencies
        run: pipenv install --dev
      - name: Lance les tests
        run: |
          pipenv run pytest test/*
      - run: echo "ğŸ This job's status is ${{ job.status }}."
